language: python
sudo: false
cache: pip

python:
   - '2.7'
   - '3.4'
   - '3.5'
   - '3.6'

matrix:
   include:
      - env: TOXENV=docs
        python: '3.6'
      - env: TOXENV=lint
        python: '3.6'
  
install:
- pip install tox tox-travis
script:
- tox
