sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=master
  - DJANGO_VERSION=1.9.x
  - DJANGO_VERSION=1.8.x
  - DJANGO_VERSION=1.7.x
  - DJANGO_VERSION=1.6.x
  - DJANGO_VERSION=1.5.x
install:
  - pip install tox
script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"
matrix:
  exclude:
   - python: "2.6"
     env: DJANGO_VERSION=master
   - python: "2.6"
     env: DJANGO_VERSION=1.7.x
   - python: "2.6"
     env: DJANGO_VERSION=1.8.x
   - python: "2.6"
     env: DJANGO_VERSION=1.9.x
   - python: "3.3"
     env: DJANGO_VERSION=1.9.x
   - python: "3.3"
     env: DJANGO_VERSION=master
   - python: "3.5"
     env: DJANGO_VERSION=1.5.x
   - python: "3.5"
     env: DJANGO_VERSION=1.6.x
   - python: "3.5"
     env: DJANGO_VERSION=1.7.x
   - python: "3.5"
     env: DJANGO_VERSION=1.8.x
cache:
  directories:
    - $HOME/.cache/pip
